name: Ansible HTTP healthcheck

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run healthcheck playbook
        run: ansible-playbook healthcheck.yml -c local
