---
# =============================================================================
# EdgePaaS Deployment Pipeline (Blue-Green) with Docker
# =============================================================================

# -----------------------------
# Capture and Resolve Host Ports
# -----------------------------

- name: Capture supplied host ports from environment
  ansible.builtin.set_fact:
    supplied_active_port: "{{ lookup('env', 'ACTIVE_HOST_PORT') | default('0') }}"
    supplied_inactive_port: "{{ lookup('env', 'INACTIVE_HOST_PORT') | default('0') }}"

- name: Resolve final ports (bootstrap defaults if 0 or empty)
  ansible.builtin.set_fact:
    resolved_active_port: "{{ (supplied_active_port | int) if (supplied_active_port | int) > 0 else 8080 }}"
    resolved_inactive_port: "{{ (supplied_inactive_port | int) if (supplied_inactive_port | int) > 0 else 8081 }}"

- name: Inform if default ports are used
  ansible.builtin.debug:
    msg: "Complete host ports NOT supplied, using defaults: ACTIVE={{ resolved_active_port }}, INACTIVE={{ resolved_inactive_port }}"
  when: supplied_active_port | int == 0 or supplied_inactive_port | int == 0

- name: Validate resolved host ports
  ansible.builtin.assert:
    that:
      - (resolved_active_port | int) != (resolved_inactive_port | int)
      - (resolved_active_port | int) > 0
      - (resolved_inactive_port | int) > 0
      - (resolved_active_port | int) < 65536
      - (resolved_inactive_port | int) < 65536
    fail_msg: >
      Invalid host port configuration.
      ACTIVE={{ resolved_active_port }},
      INACTIVE={{ resolved_inactive_port }}

- name: Show final host ports to be used
  ansible.builtin.debug:
    msg:
      - "Stable ACTIVE   → {{ resolved_active_port }}"
      - "Stable INACTIVE → {{ resolved_inactive_port }}"

# -----------------------------
# Docker Filesystem Setup
# -----------------------------

- name: Create directories for app
  ansible.builtin.file:
    path: /opt/edgepaas/app
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'

- name: Copy docker disk setup script
  ansible.builtin.copy:
    src: files/setup_docker_disk.sh
    dest: /usr/local/bin/setup_docker_disk.sh
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Run docker disk setup script
  ansible.builtin.command: /usr/local/bin/setup_docker_disk.sh
  become: true
  register: docker_disk_result
  changed_when: "'already configured' not in docker_disk_result.stdout"

- name: Ensure docker mount exists
  ansible.builtin.wait_for:
    path: /var/lib/docker
    state: present
    timeout: 60

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true

# -----------------------------
# Pull Docker Images
# -----------------------------

- name: Normalize BUILD_VERSION
  ansible.builtin.set_fact:
    effective_image_tag: >-
      {{
        (BUILD_VERSION is defined
         and BUILD_VERSION | lower != 'false'
         and BUILD_VERSION | length > 6)
        | ternary(BUILD_VERSION, 'latest')
      }}

- name: Which Is Pulled (Cached or Fresh)?
  ansible.builtin.debug:
    msg:
      - "Pulling {{ DOCKER_USER }}/{{ APP_NAME }}:{{ effective_image_tag }}-blue"
      - "Pulling {{ DOCKER_USER }}/{{ APP_NAME }}:{{ effective_image_tag }}-green"

- name: Pull Docker images
  ansible.builtin.docker_image:
    name: "{{ DOCKER_USER }}/{{ APP_NAME }}:{{ effective_image_tag }}-{{ item }}"
    source: pull
    force_source: true
  loop:
    - blue
    - green

# -----------------------------
# Load Active Color
# -----------------------------

- name: Load active color if exists
  ansible.builtin.slurp:
    src: /opt/edgepaas/ACTIVE_COLOR
  register: active_color_file
  ignore_errors: true

- name: Bootstrap active_color on first deployment
  ansible.builtin.set_fact:
    active_color: blue
  when: active_color_file is failed

- name: Set active_color from persisted state
  ansible.builtin.set_fact:
    active_color: "{{ active_color_file.content | b64decode }}"
  when: active_color_file is succeeded

- name: Derive inactive color
  ansible.builtin.set_fact:
    inactive_color: "{{ 'green' if active_color == 'blue' else 'blue' }}"

# -----------------------------
# Derive Current Nginx Ports
# -----------------------------

- name: Derive nginx ports from active color
  ansible.builtin.set_fact:
    nginx_active_port: "{{ resolved_active_port if active_color == 'blue' else resolved_inactive_port }}"
    nginx_inactive_port: "{{ resolved_inactive_port if active_color == 'blue' else resolved_active_port }}"

- name: Show current host ports before Swap
  ansible.builtin.debug:
    msg:
      - "Current ACTIVE   → {{ active_color }} on {{ nginx_active_port }}"
      - "Current INACTIVE → {{ inactive_color }} on {{ nginx_inactive_port }}"

# -----------------------------
# Stop and Remove Inactive Containers
# -----------------------------

- name: Get all inactive containers
  ansible.builtin.shell: >
    docker ps -a --filter "name={{ APP_NAME }}-{{ inactive_color }}" --format "{{ '{{.Names}}' }}"
  register: container_on_inactive
  changed_when: false
  ignore_errors: true

- name: Log inactive container status
  ansible.builtin.debug:
    msg: >-
      {% if container_on_inactive.stdout_lines %}
        [EDGEPAAS_WARNING] Inactive container(s) {{ container_on_inactive.stdout_lines | join(', ') }}
        will be stopped and removed (port {{ nginx_inactive_port }}).
      {% else %}
        No container running on inactive color {{ inactive_color }} (port {{ nginx_inactive_port }}).
      {% endif %}

- name: Stop and remove all inactive containers
  ansible.builtin.docker_container:
    name: "{{ item }}"
    state: absent
    force_kill: yes
  loop: "{{ container_on_inactive.stdout_lines }}"
  when: container_on_inactive.stdout_lines | length > 0

- name: Recheck inactive container removal
  ansible.builtin.shell: >
    docker ps -a --filter "name={{ APP_NAME }}-{{ inactive_color }}" --format "{{ '{{.Names}}' }}"
  register: container_check_after_removal
  changed_when: false
  ignore_errors: true

- name: Fail if any inactive container still exists
  ansible.builtin.fail:
    msg: >-
      [EDGEPAAS_CRITICAL] Container(s) {{ container_check_after_removal.stdout_lines | join(', ') }}
      still exist on inactive color {{ inactive_color }} (port {{ nginx_inactive_port }}). Deployment cannot continue!
  when: container_check_after_removal.stdout_lines | length > 0

- name: Log inactive container successfully removed
  ansible.builtin.debug:
    msg: "[EDGEPAAS_OK] Inactive container successfully removed. Port {{ nginx_inactive_port }} is free for deployment."
  when: container_check_after_removal.stdout_lines | length == 0

# -----------------------------
# Deploy New Container on Inactive Slot
# -----------------------------

- name: Start new container on inactive slot
  ansible.builtin.docker_container:
    name: "{{ APP_NAME }}-{{ inactive_color }}"
    image: "{{ DOCKER_USER }}/{{ APP_NAME }}:{{ effective_image_tag }}-{{ inactive_color }}"
    state: started
    restart_policy: always
    ports:
      - "{{ nginx_inactive_port }}:{{ container_port | default(80) }}"
    env:
      DATABASE_URL: "{{ DATABASE_URL }}"
      CONTAINER_PORT: "{{ container_port | default(80) | string }}"
      RUN_MIGRATIONS: "{{ RUN_MIGRATIONS }}"
      USE_SQLITE: "{{ USE_SQLITE }}"
      BOTH_DB: "{{ BOTH_DB }}"
    env_file: /opt/edgepaas/.env.test

- name: Determine source of DATABASE_URL
  ansible.builtin.set_fact:
    database_url_source: >-
      {% if lookup('env','DATABASE_URL') | length > 0 %}
        environment variable
      {% else %}
        .env file (/opt/edgepaas/.env.test)
      {% endif %}

- name: Show which DATABASE_URL source is used
  ansible.builtin.debug:
    msg: "DATABASE_URL is taken from {{ database_url_source }}"

# -----------------------------
# Healthcheck
# -----------------------------

- name: Wait for mapped inactive port to be open
  wait_for:
    host: "{{ health_host }}"
    port: "{{ nginx_inactive_port }}"
    timeout: 10
  ignore_errors: true

- name: HTTP check against mapped port
  uri:
    url: "http://{{ health_host }}:{{ nginx_inactive_port }}"
    method: GET
    status_code: 200
    timeout: 5
  register: health_check_port
  retries: 5
  delay: 3
  until: health_check_port.status == 200
  ignore_errors: true

- name: HTTP check /health endpoint
  uri:
    url: "http://{{ health_host }}:{{ nginx_inactive_port }}/health"
    method: GET
    status_code: 200
    timeout: 5
  register: health_check_endpoint
  retries: 5
  delay: 5
  until: health_check_endpoint.status == 200
  ignore_errors: true

- name: Show healthcheck results
  ansible.builtin.debug:
    msg:
      - "Port check status: {{ health_check_port.status }}"
      - "/health endpoint status: {{ health_check_endpoint.status }}"

# -----------------------------
# Failure Alert
# -----------------------------

- name: Send alert email if health check failed
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ EMAIL_FROM }}"
    password: "{{ EMAIL_PASS }}"
    to: "{{ EMAIL_TO }}"
    subject: "❌ EdgePaaS Health Check Failure"
    body: |
      Pipeline Health check failed at {{ ansible_date_time.iso8601 }}!
      -  Port status: {{ health_check_port.status }}
      - /health status: {{ health_check_endpoint.status }}
  when: health_check_port.status != 200 or health_check_endpoint.status != 200

- name: Fail if any health check failed
  fail:
    msg: |
      ❌ Health check failed! Details:
      - Port check status: {{ health_check_port.status }}
      - /health endpoint status: {{ health_check_endpoint.status }}
  when: health_check_port.status != 200 or health_check_endpoint.status != 200

# -----------------------------
# Swap and Activate New Version
# -----------------------------

- name: Define nginx swap intent
  ansible.builtin.set_fact:
    next_active_color: "{{ inactive_color }}"
    next_active_port: "{{ nginx_inactive_port }}"
    rollback_color: "{{ active_color }}"
    rollback_port: "{{ nginx_active_port }}"

- name: Debug nginx switch intent result
  ansible.builtin.debug:
    msg:
      - "Switching nginx to:"
      - "NEW ACTIVE → {{ next_active_color }} on {{ next_active_port }}"
      - "ROLLBACK   → {{ rollback_color }} on {{ rollback_port }}"

- name: Update nginx to new active container
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/edgepaas.conf
    owner: root
    group: root
    mode: '0644'
    force: true
  vars:
    active_port: "{{ next_active_port }}"
    inactive_port: "{{ rollback_port }}"
  become: true
  notify: Reload nginx

# - meta: flush_handlers

- name: Freeze swap state
  ansible.builtin.set_fact:
    new_active_color: "{{ next_active_color }}"
    new_active_port: "{{ next_active_port }}"
    old_active_color: "{{ rollback_color }}"
    old_active_port: "{{ rollback_port }}"

- name: Persist active color
  ansible.builtin.copy:
    content: "{{ new_active_color }}"
    dest: /opt/edgepaas/ACTIVE_COLOR

- name: Show final state
  ansible.builtin.debug:
    msg:
      - "ACTIVE   → {{ new_active_color }} on {{ new_active_port }}"
      - "OLD      → {{ old_active_color }} on {{ old_active_port }}"

- name: Test nginx config
  ansible.builtin.command: nginx -t
  become: true

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true

- name: Rollback window emergency
  ansible.builtin.pause:
    minutes: 1

