---
# =============================================================================
# EdgePaaS EC2 Preparation & Environment Setup Tasks
# =============================================================================

# -----------------------------
# General Info About Pipeline
# ----------------------------
- name: Deployment Notice
  ansible.builtin.debug:
    msg: >
      EdgePaaS uses self-managed blue/green deployment.
      Active color is derived from persisted state.
      Do not pass color vars manually.

# -----------------------------
# Environment Variable Checks
# -----------------------------

- name: Define required variables list
  ansible.builtin.set_fact:
    required_vars:
      - BUILD_VERSION
      - DOCKER_USER
      - APP_NAME
      - EC2_IP
      - DATABASE_URL
      - OPENWEATHER_API_KEY
      - RUN_MIGRATIONS
      - USE_SQLITE
      - BOTH_DB
      - ANSIBLE_HOST_KEY_CHECKING
      - EMAIL_FROM
      - EMAIL_TO
      - EMAIL_PASS

- name: Ensure required variables exist (env or extra-vars)
  ansible.builtin.assert:
    that:
      - >
        (
          hostvars[inventory_hostname].get(item)
          | default('', true)
          | string
        ) != ''
        or
        (
          lookup('env', item)
          | default('', true)
          | string
        ) != ''
    fail_msg: "❌ Required variable '{{ item }}' is missing or empty!"
    success_msg: "✅ Variable '{{ item }}' detected."
  loop: "{{ required_vars }}"
  loop_control:
    label: "{{ item }}"

- name: Promote all required variables to host facts
  ansible.builtin.set_fact:
    "{{ item }}": >-
      {{
        hostvars[inventory_hostname].get(item)
        | default(lookup('env', item), true)
      }}
  loop: "{{ required_vars }}"
  loop_control:
    label: "{{ item }}"

- name: Debug - Environment Variables Check Complete
  ansible.builtin.debug:
    msg: "✅ All required environment variables are defined for {{ inventory_hostname }}"

# -----------------------------
# Host Identification
# -----------------------------

- name: Set default health_host
  ansible.builtin.set_fact:
    health_host: "{{ health_host | default('127.0.0.1') }}"

- name: Identify remote host
  ansible.builtin.command:
    cmd: hostname
  register: host_out

- name: Show execution context
  ansible.builtin.debug:
    msg:
      - "Running on host      → {{ host_out.stdout }}"
      - "Inventory hostname   → {{ inventory_hostname }}"
      - "Connection type      → {{ ansible_connection | default('ssh') }}"

# -----------------------------
# CI/CD Detection and Host Setup
# -----------------------------

- name: Detect if running in CI/CD
  ansible.builtin.set_fact:
    is_cicd: "{{ lookup('env','GITHUB_ACTIONS') | default(false) | bool }}"

- name: Debug CI/CD detection
  ansible.builtin.debug:
    msg: "Running in CI/CD? {{ is_cicd }}"

- name: Set ansible_host explicitly for CI/CD
  ansible.builtin.set_fact:
    ansible_host: "{{ lookup('env', 'EC2_IP') }}"
  when: is_cicd

- name: Debug ansible_host
  ansible.builtin.debug:
    msg: "Connecting to Ansible_host: {{ ansible_host }}"

- name: Set health check host
  ansible.builtin.set_fact:
    health_host: "127.0.0.1"


# -----------------------------
# Basic OS Preparation
# -----------------------------

- name: Get Host IP
  ansible.builtin.set_fact:
    private_ip: "{{ ansible_facts['default_ipv4']['address'] }}"

- name: Update package metadata only (safe for AL2023)
  ansible.builtin.yum:
    update_cache: true

- name: Ensure deploy user exists
  ansible.builtin.user:
    name: deploy
    comment: "EdgePaaS deploy user"
    shell: /bin/bash
    state: present
    create_home: yes

- name: Allow deploy user passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'
  become: yes
  become_user: root

# -----------------------------
# Nginx Installation & Setup
# -----------------------------

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Ensure nginx conf.d directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

# -----------------------------
# Logging Directory
# -----------------------------

- name: Ensure log directory exists
  ansible.builtin.file:
    path: /var/log/edgepaas
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

# -----------------------------
# Database Client Setup (PostgreSQL + SQLite fallback)
# -----------------------------

- name: Install PostgreSQL client (no server) and SSL deps
  become: true
  ansible.builtin.yum:
    name:
      - postgresql15
      - openssl
      - ca-certificates
    state: present

- name: Install Python DB libraries (no libpq-devel)
  become: true
  ansible.builtin.yum:
    name:
      - python3-psycopg2
      - sqlite
    state: present

# -----------------------------
# Environment Configuration (.env)
# -----------------------------

- name: Write DB environment file
  ansible.builtin.copy:
    dest: /opt/edgepaas/.env.test
    owner: ec2-user
    group: ec2-user
    mode: '0644'
    content: |
      DATABASE_URL={{ DATABASE_URL }}
      DATABASE_URL_SQLITE=sqlite:////tmp/edgepaas/fallback.db

- name: Debug - DB client setup complete
  ansible.builtin.debug:
    msg: >
      PostgreSQL client installed.
      SQLite fallback ready.
      No local PostgreSQL server installed.

# -----------------------------
# Task Finish Info
# -----------------------------

- name: First Task finished info
  set_fact:
    task_finished_at: "{{ '%Y-%m-%d %H:%M:%S' | strftime }}"

- debug:
    msg: "✅ Prep tasks finished at {{ task_finished_at }}"

