---
# =============================================================================
# EdgePaaS EC2 Preparation & Local Postgres Setup Tasks
# =============================================================================


# -----------------------------
# Requirements
# -----------------------------
- name: Ensure required environment variables or extra-vars are set
  block:
    - name: Set required vars list
      set_fact:
        required_vars:
          - DOCKER_USER
          - APP_NAME
          - EC2_IP
          - DATABASE_URL
          - OPENWEATHER_API_KEY
          - RUN_MIGRATIONS
          - ANSIBLE_HOST_KEY_CHECKING
          - EMAIL_FROM
          - EMAIL_TO
          - EMAIL_PASS

    # Verify each variable exists (from extra-vars or env)
    - name: Verify required variables exist (env or extra-vars)
      ansible.builtin.assert:
        that:
          - ((vars[item] is defined and vars[item] | length > 0) or (lookup('env', item) | length > 0))
        fail_msg: "❌ Required variable '{{ item }}' is missing or empty!"
        success_msg: "✅ Variable '{{ item }}' detected."
      loop: "{{ required_vars }}"

# ------------------------------
# Basic OS Prep
# ------------------------------

- name: Get Host IP
  ansible.builtin.set_fact:
    private_ip: "{{ ansible_facts['default_ipv4']['address'] }}"

- name: Update package metadata only (safe for AL2023)
  ansible.builtin.yum:
    update_cache: true

- name: Ensure deploy user exists
  ansible.builtin.user:
    name: deploy
    comment: "EdgePaaS deploy user"
    shell: /bin/bash
    state: present
    create_home: yes

- name: Allow deploy user passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'
  become: yes
  become_user: root

# ------------------------------
# Nginx Installation
# ------------------------------

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Ensure nginx conf.d directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

# ------------------------------
# Logging Directory
# ------------------------------

- name: Ensure log directory exists
  ansible.builtin.file:
    path: /var/log/edgepaas
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

# ------------------------------
# Database Client Setup (Render PostgreSQL + SQLite fallback)
# ------------------------------

- name: Install PostgreSQL client (no server) and SSL deps
  become: true
  ansible.builtin.yum:
    name:
      - postgresql15
      - openssl
      - ca-certificates
    state: present

# ------------------------------
# Python DB Dependencies
# ------------------------------

- name: Install Python DB libraries (no libpq-devel)
  become: true
  ansible.builtin.yum:
    name:
      - python3-psycopg2
      - sqlite
    state: present

# ------------------------------
# SQLite Fallback Storage
# ------------------------------

- name: Ensure fallback SQLite directory exists
  become: true
  ansible.builtin.file:
    path: /opt/edgepaas
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Ensure fallback SQLite DB file exists
  become: true
  ansible.builtin.file:
    path: /opt/edgepaas/fallback.db
    state: touch
    owner: ec2-user
    group: ec2-user
    mode: '0644'

# ------------------------------
# Environment Configuration
# ------------------------------

- name: Write DB environment file
  ansible.builtin.copy:
    dest: /opt/edgepaas/.env
    owner: ec2-user
    group: ec2-user
    mode: '0644'
    content: |
      DATABASE_URL={{ DATABASE_URL }}
      DATABASE_URL_SQLITE=sqlite:////opt/edgepaas/fallback.db

- name: Debug - DB client setup complete
  ansible.builtin.debug:
    msg: >
      PostgreSQL client installed (Render DB only).
      SQLite fallback ready.
      No local PostgreSQL server installed.

# ------------------------------
# Task Finish Info
# ------------------------------

- name: First Task finished info
  set_fact:
    task_finished_at: "{{ '%Y-%m-%d %H:%M:%S' | strftime }}"

- debug:
    msg: "Task finished at {{ task_finished_at }}"
