---
# =============================================================================
# EdgePaaS EC2 Preparation & Local Postgres Setup Tasks
# =============================================================================


# Requirements
- name: Ensure required environment variables or extra-vars are set
  vars:
    required_vars:
      - DOCKER_USER
      - APP_NAME
      - EC2_IP
      - DATABASE_URL
      - OPENWEATHER_API_KEY
      - RUN_MIGRATIONS
      - ANSIBLE_HOST_KEY_CHECKING
      - EMAIL_FROM
      - EMAIL_TO
      - ALERT_EMAIL_PASSWORD
  block:
    - name: Verify required variables exist (env or extra-vars)
      ansible.builtin.assert:
        that:
          - (vars[item] is defined and vars[item] | length > 0) or (lookup('env', item) | length > 0)
        fail_msg: "❌ Required variable '{{ item }}' is missing or empty!"
        success_msg: "✅ Variable '{{ item }}' detected."
      loop: "{{ required_vars }}"

# ------------------------------
# Basic OS Prep
# ------------------------------

- name: Get Host IP
  ansible.builtin.set_fact:
    private_ip: "{{ ansible_facts['default_ipv4']['address'] }}"

- name: Update package metadata only (safe for AL2023)
  ansible.builtin.yum:
    update_cache: true

- name: Ensure deploy user exists
  ansible.builtin.user:
    name: deploy
    comment: "EdgePaaS deploy user"
    shell: /bin/bash
    state: present
    create_home: yes

- name: Allow deploy user passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'
  become: yes
  become_user: root

# ------------------------------
# Nginx Installation
# ------------------------------

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Ensure nginx conf.d directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

# ------------------------------
# Logging Directory
# ------------------------------

- name: Ensure log directory exists
  ansible.builtin.file:
    path: /var/log/edgepaas
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

# ------------------------------
# PostgreSQL Installation & Service
# ------------------------------

- name: Install PostgreSQL Server And Clinet
  become: true
  ansible.builtin.yum:
    name:
      - postgresql15
      - postgresql15-server
      - openssl-devel
    state: present

- name: Verify psql is available
  ansible.builtin.command: psql --version
  register: psql_version
  ignore_errors: yes

- name: Ensure PostgreSQL binaries are in PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/pgsql.sh
    line: 'export PATH=$PATH:/usr/pgsql-15/bin'
    create: yes

- debug:
    msg: "psql version: {{ psql_version.stdout }}"

- name: Initialize PostgreSQL database
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
  become: yes

- name: Ensure PostgreSQL is running and enabled
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Configure PostgreSQL to listen on private IP
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '{{ private_ip }}'"
  become: yes

- name: Allow private IP access to PostgreSQL
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: "^host\\s+all\\s+all\\s+{{ private_ip }}/32"
    line: "host    all             all             {{ private_ip }}/32            md5"
    insertafter: EOF
  become: yes

- name: Allow Docker subnet to connect to PostgreSQL
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    line: "host    all             all             172.17.0.0/16            md5"
    insertafter: EOF
  become: yes

- name: Restart PostgreSQL to apply network config
  ansible.builtin.service:
    name: postgresql
    state: restarted
  become: yes

- name: Wait for PostgreSQL on private IP
  ansible.builtin.wait_for:
    host: "{{ private_ip }}"
    port: 5432
    delay: 3
    timeout: 21

# ------------------------------
# PostgreSQL Test DB & User Setup (Idempotent)
# ------------------------------

- name: Ensure PostgreSQL Python libraries are installed
  ansible.builtin.yum:
    name:
      - python3-psycopg2
      - postgresql-devel
    state: present
  become: yes

- name: Ensure test user exists
  ansible.builtin.shell: |
    sudo -u postgres psql -c "DO
    \$\$ BEGIN
       IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = 'testuser') THEN
          CREATE USER testuser WITH PASSWORD 'testpass';
       END IF;
    END
    \$\$;"

- name: Ensure test database exists
  ansible.builtin.shell: |
    sudo -u postgres psql -v ON_ERROR_STOP=1 -tc "
    SELECT 1 FROM pg_database WHERE datname = 'testdb';
    " | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE testdb OWNER testuser;"

- name: Grant privileges on testdb
  ansible.builtin.shell: |
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO testuser;"

# ------------------------------
# .env.test Creation
# ------------------------------

- name: Ensure /opt/edgepaas directory exists
  ansible.builtin.file:
    path: /opt/edgepaas
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Write .env.test with dynmaic IP
  ansible.builtin.copy:
    dest: /opt/edgepaas/.env.test
    content: "DATABASE_URL_TEST=postgresql://testuser:testpass@{{ private_ip }}:5432/testdb"
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Debug - Postgres test DB setup complete
  ansible.builtin.debug:
    msg: "Test user and test database ensured. .env.test created."

# ------------------------------
# Task Finish Info
# ------------------------------

- name: First Task finished info
  set_fact:
    task_finished_at: "{{ '%Y-%m-%d %H:%M:%S' | strftime }}"

- debug:
    msg: "Task finished at {{ task_finished_at }}"
