---
# =============================================================================
# EdgePaaS EC2 Preparation & Local Postgres Setup Tasks
# =============================================================================

# ------------------------------
# Basic OS Prep
# ------------------------------

- name: Get Host IP
  ansible.builtin.set_facts:
    private_ip: "{{ ansible_default_ipv4.address}}"

- name: Update package metadata only (safe for AL2023)
  ansible.builtin.yum:
    update_cache: true

- name: Ensure deploy user exists
  ansible.builtin.user:
    name: deploy
    comment: "EdgePaaS deploy user"
    shell: /bin/bash
    state: present
    create_home: yes

- name: Allow deploy user passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'
  become: yes
  become_user: root

# ------------------------------
# Nginx Installation
# ------------------------------

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Ensure nginx conf.d directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

# ------------------------------
# Logging Directory
# ------------------------------

- name: Ensure log directory exists
  ansible.builtin.file:
    path: /var/log/edgepaas
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

# ------------------------------
# PostgreSQL Installation & Service
# ------------------------------

- name: Install PostgreSQL server and client
  become: true
  ansible.builtin.yum:
    name:
      - postgresql15
      - postgresql15-server
    state: present

- name: Initialize PostgreSQL database
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
  become: yes

- name: Ensure PostgreSQL is running and enabled
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Wait for PostgreSQL to be ready
  ansible.builtin.wait_for:
    port: 5432
    delay: 3
    timeout: 21

# ------------------------------
# PostgreSQL Test DB & User Setup (Idempotent)
# ------------------------------

- name: Ensure PostgreSQL Python libraries are installed
  ansible.builtin.yum:
    name:
      - python3-psycopg2
      - postgresql-devel
    state: present
  become: yes

- name: Ensure test user exists
  ansible.builtin.shell: |
    sudo -u postgres psql -c "DO
    \$\$ BEGIN
       IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = 'testuser') THEN
          CREATE USER testuser WITH PASSWORD 'testpass';
       END IF;
    END
    \$\$;"

- name: Ensure test database exists
  ansible.builtin.shell: |
    sudo -u postgres psql -v ON_ERROR_STOP=1 -tc "
    SELECT 1 FROM pg_database WHERE datname = 'testdb';
    " | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE testdb OWNER testuser;"

- name: Grant privileges on testdb
  ansible.builtin.shell: |
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO testuser;"

# ------------------------------
# .env.test Creation
# ------------------------------

- name: Ensure /opt/edgepaas directory exists
  ansible.builtin.file:
    path: /opt/edgepaas
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Write .env.test with dynmaic IP
  ansible.builtin.copy:
    dest: /opt/edgepaas/.env.test
    content: "DATABASE_URL_TEST=postgresql://testuser:testpass@{{ private_ip }}:5432/testdb"
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Debug - Postgres test DB setup complete
  ansible.builtin.debug:
    msg: "Test user and test database ensured. .env.test created."

# ------------------------------
# Task Finish Info
# ------------------------------

- name: First Task finished info
  set_fact:
    task_finished_at: "{{ '%Y-%m-%d %H:%M:%S' | strftime }}"

- debug:
    msg: "Task finished at {{ task_finished_at }}"
