---
- name: EdgePaaS CI/CD Orchestration
  hosts: test
  gather_facts: no
  become: true

  tasks:
    - name: Run pre-deployment checks
      import_tasks: playbook1.yml

    - name: Run deployment pipeline
      import_tasks: playbook2.yml
