---
# playbook1.yml
# Pre-deployment connectivity and runtime smoke test (SRE style)
# Logs custom messages for any failures but does not stop execution

# -------------------------------
# Ensure health_host is defined
# -------------------------------
- name: Set default health_host if not already defined
  ansible.builtin.set_fact:
    health_host: "{{ health_host | default('127.0.0.1') }}"

# -------------------------------
# Identify remote host
# -------------------------------
- name: Identify remote host
  ansible.builtin.command:
    cmd: hostname
  register: host_out

- name: Show execution context
  ansible.builtin.debug:
    msg:
      - "Running on host      → {{ host_out.stdout }}"
      - "Inventory hostname   → {{ inventory_hostname }}"
      - "Connection type      → {{ ansible_connection | default('ssh') }}"

# -------------------------------
# Port reachability checks
# -------------------------------
- name: Wait for application ports to be reachable
  ansible.builtin.wait_for:
    host: "{{ health_host }}"
    port: "{{ item }}"
    timeout: 5
  loop:
    - 8080
    - 8081
  loop_control:
    label: "Port {{ item }}"
  register: port_results
  ignore_errors: true

- name: Log port check results (SRE-style)
  ansible.builtin.debug:
    msg: >-
      {% if item.failed %}
        [EDGEPAAS_HEALTHCHECK_FAILED] Port {{ item.item }} unreachable on {{ health_host }}
      {% else %}
        [EDGEPAAS_HEALTHCHECK_OK] Port {{ item.item }} reachable on {{ health_host }}
      {% endif %}
  loop: "{{ port_results.results }}"

# -------------------------------
# HTTP checks
# -------------------------------
- name: HTTP GET checks on application ports
  ansible.builtin.uri:
    url: "http://{{ health_host }}:{{ item }}"
    method: GET
    status_code: 200
    timeout: 5
  loop:
    - 8080
    - 8081
  loop_control:
    label: "HTTP check on port {{ item }}"
  register: http_results
  ignore_errors: true

- name: Log HTTP check results (SRE-style)
  ansible.builtin.debug:
    msg: >-
      {% if item.failed %}
        [EDGEPAAS_HEALTHCHECK_FAILED] HTTP endpoint http://{{ health_host }}:{{ item.item }} not responding or status != 200
      {% else %}
        [EDGEPAAS_HEALTHCHECK_OK] HTTP endpoint http://{{ health_host }}:{{ item.item }} OK
      {% endif %}
  loop: "{{ http_results.results }}"

# -------------------------------
# /health endpoint check
# -------------------------------
- name: Check /health endpoint
  ansible.builtin.uri:
    url: "http://{{ health_host }}:8080/health"
    method: GET
    status_code: 200
    timeout: 5
  register: health_endpoint
  ignore_errors: true

- name: Log /health endpoint status
  ansible.builtin.debug:
    msg: >-
      {% if health_endpoint.failed %}
        [EDGEPAAS_HEALTHCHECK_FAILED] /health endpoint http://{{ health_host }}:8080/health not responding or status != 200
      {% else %}
        [EDGEPAAS_HEALTHCHECK_OK] /health endpoint OK
      {% endif %}

# -------------------------------
# Raw fallback connectivity test
# -------------------------------
- name: Raw curl fallback test (port 80)
  ansible.builtin.command:
    cmd: curl -v http://{{ health_host }}:80
  register: curl_result
  ignore_errors: true

- name: Log raw curl test result
  ansible.builtin.debug:
    msg: >-
      {% if curl_result.failed %}
        [EDGEPAAS_HEALTHCHECK_FAILED] Raw curl test failed on {{ health_host }}:80
      {% else %}
        [EDGEPAAS_HEALTHCHECK_OK] Raw curl test succeeded on {{ health_host }}:80
      {% endif %}

# -------------------------------
# Summary
# -------------------------------
- name: Health check completed
  ansible.builtin.debug:
    msg: "✅ Pre-deployment connectivity and runtime checks completed on {{ inventory_hostname }}"
